import About from "@/components/About"
import Main from "@/components/Main"
import Navbar from "@/components/Navbar"
import Skills from "@/components/Skills"
import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prathamesh | Frontend Dev</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
    </div>
  )
}
